installed_at: '2026-03-03T14:24:38+00:00'
skill_id: git/mastering-typescript
git_repo: https://github.com/SpillwaveSolutions/mastering-typescript-skill
skill_path: /tmp/skilz-git-96gytl6o/mastering-typescript
git_sha: 2f74a00f731f2ea4d48f45d852067a7be8efd0d1
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
